# Generated by Django 2.0.7 on 2018-07-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_except_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_group', to='api.Group'),
        ),
    ]
