# Generated by Django 2.0.7 on 2018-07-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmt_activity', to='api.Activity'),
        ),
    ]
