# Generated by Django 2.0.7 on 2018-07-10 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180709_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='except_users',
            field=models.ManyToManyField(blank=True, related_name='except_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
